export const formatCountryUrl = (country: string) => {
  return country.replace(/\s+/g, '').toLowerCase();
};

export const getCountryName = (pathname: string) => {
  return pathname.split('/')[1];
};

export const countries = [
  { countryEng: 'Ghana', countryKor: '가나' },
  { countryEng: 'Gabon', countryKor: '가봉' },
  { countryEng: 'Guyana', countryKor: '가이아나' },
  { countryEng: 'Gambia', countryKor: '감비아' },
  { countryEng: 'Guatemala', countryKor: '과테말라' },
  { countryEng: 'Grenada', countryKor: '그레나다' },
  { countryEng: 'Greece', countryKor: '그리스' },
  { countryEng: 'Guinea', countryKor: '기니' },
  { countryEng: 'Guinea-Bissau', countryKor: '기니비사우' },
  { countryEng: 'Namibia', countryKor: '나미비아' },
  { countryEng: 'Nauru', countryKor: '나우루' },
  { countryEng: 'Nigeria', countryKor: '나이지리아' },
  { countryEng: 'South Sudan', countryKor: '남수단' },
  { countryEng: 'South Africa', countryKor: '남아프리카공화국' },
  { countryEng: 'Netherlands', countryKor: '네덜란드' },
  { countryEng: 'Nepal', countryKor: '네팔' },
  { countryEng: 'Norway', countryKor: '노르웨이' },
  { countryEng: 'New Zealand', countryKor: '뉴질랜드' },
  { countryEng: 'Niger', countryKor: '니제르' },
  { countryEng: 'Nicaragua', countryKor: '니카라과' },
  { countryEng: 'South Korea', countryKor: '대한민국' },
  { countryEng: 'Denmark', countryKor: '덴마크' },
  { countryEng: 'Dominican Republic', countryKor: '도미니카공화국' },
  { countryEng: 'Dominica', countryKor: '도미니카' },
  { countryEng: 'Germany', countryKor: '독일' },
  { countryEng: 'East Timor', countryKor: '동티모르' },
  { countryEng: 'Laos', countryKor: '라오스' },
  { countryEng: 'Liberia', countryKor: '라이베리아' },
  { countryEng: 'Latvia', countryKor: '라트비아' },
  { countryEng: 'Russia', countryKor: '러시아' },
  { countryEng: 'Lebanon', countryKor: '레바논' },
  { countryEng: 'Lesotho', countryKor: '레소토' },
  { countryEng: 'Romania', countryKor: '루마니아' },
  { countryEng: 'Luxembourg', countryKor: '룩셈부르크' },
  { countryEng: 'Rwanda', countryKor: '르완다' },
  { countryEng: 'Libya', countryKor: '리비아' },
  { countryEng: 'Lithuania', countryKor: '리투아니아' },
  { countryEng: 'Liechtenstein', countryKor: '리히텐슈타인' },
  { countryEng: 'Madagascar', countryKor: '마다가스카르' },
  { countryEng: 'Marshall Islands', countryKor: '마셜 제도' },
  { countryEng: 'Malawi', countryKor: '말라위' },
  { countryEng: 'Malaysia', countryKor: '말레이시아' },
  { countryEng: 'Mali', countryKor: '말리' },
  { countryEng: 'Mexico', countryKor: '멕시코' },
  { countryEng: 'Monaco', countryKor: '모나코' },
  { countryEng: 'Morocco', countryKor: '모로코' },
  { countryEng: 'Mauritius', countryKor: '모리셔스' },
  { countryEng: 'Mauritania', countryKor: '모리타니아' },
  { countryEng: 'Mozambique', countryKor: '모잠비크' },
  { countryEng: 'Montenegro', countryKor: '몬테네그로' },
  { countryEng: 'Moldova', countryKor: '몰도바' },
  { countryEng: 'Maldives', countryKor: '몰디브' },
  { countryEng: 'Malta', countryKor: '몰타' },
  { countryEng: 'Mongolia', countryKor: '몽골' },
  { countryEng: 'United States', countryKor: '미국' },
  { countryEng: 'Myanmar', countryKor: '미얀마' },
  {
    countryEng: 'Federated States of Micronesia',
    countryKor: '미크로네시아 연방',
  },
  { countryEng: 'Vanuatu', countryKor: '바누아투' },
  { countryEng: 'Bahrain', countryKor: '바레인' },
  { countryEng: 'Barbados', countryKor: '바베이도스' },
  { countryEng: 'Bahamas', countryKor: '바하마' },
  { countryEng: 'Bangladesh', countryKor: '방글라데시' },
  { countryEng: 'Benin', countryKor: '베냉' },
  { countryEng: 'Venezuela', countryKor: '베네수엘라' },
  { countryEng: 'Vietnam', countryKor: '베트남' },
  { countryEng: 'Belgium', countryKor: '벨기에' },
  { countryEng: 'Belarus', countryKor: '벨라루스' },
  { countryEng: 'Belize', countryKor: '벨리즈' },
  {
    countryEng: 'Bosnia and Herzegovina',
    countryKor: '보스니아 헤르체고비나',
  },
  { countryEng: 'Botswana', countryKor: '보츠와나' },
  { countryEng: 'Bolivia', countryKor: '볼리비아' },
  { countryEng: 'Burundi', countryKor: '부룬디' },
  { countryEng: 'Burkina Faso', countryKor: '부르키나파소' },
  { countryEng: 'Bhutan', countryKor: '부탄' },
  { countryEng: 'North Macedonia', countryKor: '북마케도니아' },
  { countryEng: 'North Korea', countryKor: '북한' },
  { countryEng: 'Bulgaria', countryKor: '불가리아' },
  { countryEng: 'Brazil', countryKor: '브라질' },
  { countryEng: 'Brunei', countryKor: '브루나이' },
  { countryEng: 'Samoa', countryKor: '사모아' },
  { countryEng: 'Saudi Arabia', countryKor: '사우디아라비아' },
  { countryEng: 'San Marino', countryKor: '산마리노' },
  {
    countryEng: 'São Tomé and Príncipe',
    countryKor: '상투메 프린시페',
  },
  { countryEng: 'Senegal', countryKor: '세네갈' },
  { countryEng: 'Serbia', countryKor: '세르비아' },
  { countryEng: 'Seychelles', countryKor: '세이셸' },
  { countryEng: 'Saint Lucia', countryKor: '세인트루시아' },
  {
    countryEng: 'Saint Vincent and the Grenadines',
    countryKor: '세인트빈센트그레나딘',
  },
  {
    countryEng: 'Saint Kitts and Nevis',
    countryKor: '세인트키츠네비스',
  },
  { countryEng: 'Somalia', countryKor: '소말리아' },
  { countryEng: 'Solomon Islands', countryKor: '솔로몬 제도' },
  { countryEng: 'Sudan', countryKor: '수단' },
  { countryEng: 'Suriname', countryKor: '수리남' },
  { countryEng: 'Sri Lanka', countryKor: '스리랑카' },
  { countryEng: 'Sweden', countryKor: '스웨덴' },
  { countryEng: 'Switzerland', countryKor: '스위스' },
  { countryEng: 'Spain', countryKor: '스페인' },
  { countryEng: 'Slovakia', countryKor: '슬로바키아' },
  { countryEng: 'Slovenia', countryKor: '슬로베니아' },
  { countryEng: 'Syria', countryKor: '시리아' },
  { countryEng: 'Sierra Leone', countryKor: '시에라리온' },
  { countryEng: 'Singapore', countryKor: '싱가포르' },
  { countryEng: 'United Arab Emirates', countryKor: '아랍에미리트' },
  { countryEng: 'Armenia', countryKor: '아르메니아' },
  { countryEng: 'Argentina', countryKor: '아르헨티나' },
  { countryEng: 'Iceland', countryKor: '아이슬란드' },
  { countryEng: 'Haiti', countryKor: '아이티' },
  { countryEng: 'Ireland', countryKor: '아일랜드' },
  { countryEng: 'Azerbaijan', countryKor: '아제르바이잔' },
  { countryEng: 'Afghanistan', countryKor: '아프가니스탄' },
  { countryEng: 'Andorra', countryKor: '안도라' },
  { countryEng: 'Albania', countryKor: '알바니아' },
  { countryEng: 'Algeria', countryKor: '알제리' },
  { countryEng: 'Angola', countryKor: '앙골라' },
  { countryEng: 'Antigua and Barbuda', countryKor: '앤티가 바부다' },
  { countryEng: 'Eritrea', countryKor: '에리트레아' },
  { countryEng: 'Eswatini', countryKor: '에스와티니' },
  { countryEng: 'Estonia', countryKor: '에스토니아' },
  { countryEng: 'Ecuador', countryKor: '에콰도르' },
  { countryEng: 'Ethiopia', countryKor: '에티오피아' },
  { countryEng: 'El Salvador', countryKor: '엘살바도르' },
  { countryEng: 'United Kingdom', countryKor: '영국' },
  { countryEng: 'Yemen', countryKor: '예멘' },
  { countryEng: 'Oman', countryKor: '오만' },
  { countryEng: 'Austria', countryKor: '오스트리아' },
  { countryEng: 'Honduras', countryKor: '온두라스' },
  { countryEng: 'Jordan', countryKor: '요르단' },
  { countryEng: 'Uganda', countryKor: '우간다' },
  { countryEng: 'Uruguay', countryKor: '우루과이' },
  { countryEng: 'Uzbekistan', countryKor: '우즈베키스탄' },
  { countryEng: 'Ukraine', countryKor: '우크라이나' },
  { countryEng: 'Iraq', countryKor: '이라크' },
  { countryEng: 'Iran', countryKor: '이란' },
  { countryEng: 'Israel', countryKor: '이스라엘' },
  { countryEng: 'Egypt', countryKor: '이집트' },
  { countryEng: 'Italy', countryKor: '이탈리아' },
  { countryEng: 'India', countryKor: '인도' },
  { countryEng: 'Indonesia', countryKor: '인도네시아' },
  { countryEng: 'Japan', countryKor: '일본' },
  { countryEng: 'Jamaica', countryKor: '자메이카' },
  { countryEng: 'Zambia', countryKor: '잠비아' },
  { countryEng: 'Equatorial Guinea', countryKor: '적도 기니' },
  { countryEng: 'Georgia', countryKor: '조지아' },
  { countryEng: 'China', countryKor: '중국' },
  { countryEng: 'Central African Republic', countryKor: '중앙아프리카공화국' },
  { countryEng: 'Djibouti', countryKor: '지부티' },
  { countryEng: 'Zimbabwe', countryKor: '짐바브웨' },
  { countryEng: 'Chad', countryKor: '차드' },
  { countryEng: 'Czech Republic', countryKor: '체코' },
  { countryEng: 'Chile', countryKor: '칠레' },
  { countryEng: 'Cameroon', countryKor: '카메룬' },
  { countryEng: 'Cape Verde', countryKor: '카보베르데' },
  { countryEng: 'Kazakhstan', countryKor: '카자흐스탄' },
  { countryEng: 'Qatar', countryKor: '카타르' },
  { countryEng: 'Cambodia', countryKor: '캄보디아' },
  { countryEng: 'Canada', countryKor: '캐나다' },
  { countryEng: 'Kenya', countryKor: '케냐' },
  { countryEng: 'Comoros', countryKor: '코모로' },
  { countryEng: 'Costa Rica', countryKor: '코스타리카' },
  { countryEng: 'Ivory Coast', countryKor: '코트디부아르' },
  { countryEng: 'Colombia', countryKor: '콜롬비아' },
  { countryEng: 'Republic of the Congo', countryKor: '콩고공화국' },
  {
    countryEng: 'Democratic Republic of the Congo',
    countryKor: '콩고민주공화국',
  },
  { countryEng: 'Cuba', countryKor: '쿠바' },
  { countryEng: 'Kuwait', countryKor: '쿠웨이트' },
  { countryEng: 'Croatia', countryKor: '크로아티아' },
  { countryEng: 'Kyrgyzstan', countryKor: '키르기스스탄' },
  { countryEng: 'Kiribati', countryKor: '키리바시' },
  { countryEng: 'Cyprus', countryKor: '키프로스' },
  { countryEng: 'Tajikistan', countryKor: '타지키스탄' },
  { countryEng: 'Tanzania', countryKor: '탄자니아' },
  { countryEng: 'Thailand', countryKor: '태국' },
  { countryEng: 'Togo', countryKor: '토고' },
  { countryEng: 'Tonga', countryKor: '통가' },
  { countryEng: 'Turkmenistan', countryKor: '투르크메니스탄' },
  { countryEng: 'Tuvalu', countryKor: '투발루' },
  { countryEng: 'Tunisia', countryKor: '튀니지' },
  { countryEng: 'Turkey', countryKor: '튀르키예' },
  { countryEng: 'Trinidad and Tobago', countryKor: '트리니다드 토바고' },
  { countryEng: 'Panama', countryKor: '파나마' },
  { countryEng: 'Paraguay', countryKor: '파라과이' },
  { countryEng: 'Pakistan', countryKor: '파키스탄' },
  { countryEng: 'Papua New Guinea', countryKor: '파푸아뉴기니' },
  { countryEng: 'Palau', countryKor: '팔라우' },
  { countryEng: 'Peru', countryKor: '페루' },
  { countryEng: 'Portugal', countryKor: '포르투갈' },
  { countryEng: 'Poland', countryKor: '폴란드' },
  { countryEng: 'France', countryKor: '프랑스' },
  { countryEng: 'Fiji', countryKor: '피지' },
  { countryEng: 'Finland', countryKor: '핀란드' },
  { countryEng: 'Philippines', countryKor: '필리핀' },
  { countryEng: 'Hungary', countryKor: '헝가리' },
  { countryEng: 'Australia', countryKor: '호주' },
  { countryEng: 'Vatican City', countryKor: '바티칸시국' },
  { countryEng: 'Palestine', countryKor: '팔레스타인' },
  { countryEng: 'Cook Islands', countryKor: '쿡 제도' },
  { countryEng: 'Niue', countryKor: '니우에' },
  { countryEng: 'South Ossetia', countryKor: '남오세티야' },
  { countryEng: 'Taiwan', countryKor: '대만' },
  { countryEng: 'Northern Cyprus', countryKor: '북키프로스' },
  {
    countryEng: 'Sahrawi Arab Democratic Republic',
    countryKor: '사하라위 아랍 민주 공화국',
  },
  { countryEng: 'Somaliland', countryKor: '소말릴란드' },
  { countryEng: 'Abkhazia', countryKor: '압하지야' },
  { countryEng: 'Kosovo', countryKor: '코소보' },
];
