import { ContinentType } from '@/types/country/continent';

export const CONTINENTS: ContinentType[] = [
  {
    url: '/images/continent/asiaBg.png',
    continent: 'Asia',
    continentKor: '아시아',
    explain: '아는 만큼 보이는 매력',
  },
  {
    url: '/images/continent/europeBg.png',
    continent: 'Europe',
    continentKor: '유럽',
    explain: '상상 속 유럽 여행을 현실로',
  },
  {
    url: '/images/continent/oceaniaBg.png',
    continent: 'Oceania',
    continentKor: '오세아니아',
    explain: '수중낙원부터 만년설까지',
  },
  {
    url: '/images/continent/southAmericBg.png',
    continent: 'South America',
    continentKor: '남아메리카',
    explain: '숨겨놓은 신비로움이 한가득!',
  },
  {
    url: '/images/continent/northAmericBg.png',
    continent: 'North America',
    continentKor: '북아메리카',
    explain: '너는 어디까지 가봤니?',
  },
  {
    url: '/images/continent/africaBg.png',
    continent: 'Africa',
    continentKor: '아프리카',
    explain: '나의 첫 아프리카 여행',
  },
];

export const COUNTRY_CODE = {
  Ghana: 'GH',
  Gabon: 'GA',
  Guyana: 'GY',
  Gambia: 'GM',
  Guatemala: 'GT',
  Grenada: 'GD',
  Greece: 'GR',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Namibia: 'NA',
  Nauru: 'NR',
  Nigeria: 'NG',
  'South Sudan': 'SS',
  'South Africa': 'ZA',
  Netherlands: 'NL',
  Nepal: 'NP',
  Norway: 'NO',
  'New Zealand': 'NZ',
  Niger: 'NE',
  Nicaragua: 'NI',
  'South Korea': 'KR',
  Denmark: 'DK',
  'Dominican Republic': 'DO',
  Dominica: 'DM',
  Germany: 'DE',
  'East Timor': 'TL',
  Laos: 'LA',
  Liberia: 'LR',
  Latvia: 'LV',
  Russia: 'RU',
  Lebanon: 'LB',
  Lesotho: 'LS',
  Romania: 'RO',
  Luxembourg: 'LU',
  Rwanda: 'RW',
  Libya: 'LY',
  Lithuania: 'LT',
  Liechtenstein: 'LI',
  Madagascar: 'MG',
  'Marshall Islands': 'MH',
  Malawi: 'MW',
  Malaysia: 'MY',
  Mali: 'ML',
  Mexico: 'MX',
  Monaco: 'MC',
  Morocco: 'MA',
  Mauritius: 'MU',
  Mauritania: 'MR',
  Mozambique: 'MZ',
  Montenegro: 'ME',
  Moldova: 'MD',
  Maldives: 'MV',
  Malta: 'MT',
  Mongolia: 'MN',
  'United States': 'US',
  Myanmar: 'MM',
  'Federated States of Micronesia': 'FM',
  Vanuatu: 'VU',
  Bahrain: 'BH',
  Barbados: 'BB',
  Bahamas: 'BS',
  Bangladesh: 'BD',
  Benin: 'BJ',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Belgium: 'BE',
  Belarus: 'BY',
  Belize: 'BZ',
  'Bosnia and Herzegovina': 'BA',
  Botswana: 'BW',
  Bolivia: 'BO',
  Burundi: 'BI',
  'Burkina Faso': 'BF',
  Bhutan: 'BT',
  'North Macedonia': 'MK',
  'North Korea': 'KP',
  Bulgaria: 'BG',
  Brazil: 'BR',
  Brunei: 'BN',
  Samoa: 'WS',
  'Saudi Arabia': 'SA',
  'San Marino': 'SM',
  'São Tomé and Príncipe': 'ST',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  'Saint Lucia': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  'Saint Kitts and Nevis': 'KN',
  Somalia: 'SO',
  'Solomon Islands': 'SB',
  Sudan: 'SD',
  Suriname: 'SR',
  'Sri Lanka': 'LK',
  Sweden: 'SE',
  Switzerland: 'CH',
  Spain: 'ES',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Syria: 'SY',
  'Sierra Leone': 'SL',
  Singapore: 'SG',
  'United Arab Emirates': 'AE',
  Armenia: 'AM',
  Argentina: 'AR',
  Iceland: 'IS',
  Haiti: 'HT',
  Ireland: 'IE',
  Azerbaijan: 'AZ',
  Afghanistan: 'AF',
  Andorra: 'AD',
  Albania: 'AL',
  Algeria: 'DZ',
  Angola: 'AO',
  'Antigua and Barbuda': 'AG',
  Eritrea: 'ER',
  Eswatini: 'SZ',
  Estonia: 'EE',
  Ecuador: 'EC',
  Ethiopia: 'ET',
  'El Salvador': 'SV',
  'United Kingdom': 'GB',
  Yemen: 'YE',
  Oman: 'OM',
  Austria: 'AT',
  Honduras: 'HN',
  Jordan: 'JO',
  Uganda: 'UG',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Ukraine: 'UA',
  Iraq: 'IQ',
  Iran: 'IR',
  Israel: 'IL',
  Egypt: 'EG',
  Italy: 'IT',
  India: 'IN',
  Indonesia: 'ID',
  Japan: 'JP',
  Jamaica: 'JM',
  Zambia: 'ZM',
  'Equatorial Guinea': 'GQ',
  Georgia: 'GE',
  China: 'CN',
  'Central African Republic': 'CF',
  Djibouti: 'DJ',
  Zimbabwe: 'ZW',
  Chad: 'TD',
  'Czech Republic': 'CZ',
  Chile: 'CL',
  Cameroon: 'CM',
  'Cape Verde': 'CV',
  Kazakhstan: 'KZ',
  Qatar: 'QA',
  Cambodia: 'KH',
  Canada: 'CA',
  Kenya: 'KE',
  Comoros: 'KM',
  'Costa Rica': 'CR',
  'Ivory Coast': 'CI',
  Colombia: 'CO',
  'Republic of the Congo': 'CG',
  'Democratic Republic of the Congo': 'CD',
  Cuba: 'CU',
  Kuwait: 'KW',
  Croatia: 'HR',
  Kyrgyzstan: 'KG',
  Kiribati: 'KI',
  Cyprus: 'CY',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  Thailand: 'TH',
  Togo: 'TG',
  Tonga: 'TO',
  Turkmenistan: 'TM',
  Tuvalu: 'TV',
  Tunisia: 'TN',
  Turkey: 'TR',
  'Trinidad and Tobago': 'TT',
  Panama: 'PA',
  Paraguay: 'PY',
  Pakistan: 'PK',
  'Papua New Guinea': 'PG',
  Palau: 'PW',
  Peru: 'PE',
  Portugal: 'PT',
  Poland: 'PL',
  France: 'FR',
  Fiji: 'FJ',
  Finland: 'FI',
  Philippines: 'PH',
  Hungary: 'HU',
  Australia: 'AU',
  'Vatican City': 'VA',
  Palestine: 'PS',
  'Cook Islands': 'CK',
  Niue: 'NU',
  'South Ossetia': 'XSO',
  Taiwan: 'TW',
  'Northern Cyprus': 'NCY',
  'Sahrawi Arab Democratic Republic': 'SADR',
  Somaliland: 'SML',
  Abkhazia: 'ABK',
  Kosovo: 'XK',
};
